import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Layout/Navbar";
import Footer from "@/Component/Layout/Footer";
import { AuthProvider } from "@/Component/AuthProvider/AuthProvider";
import { CartProvider } from "@/Component/Context/Context";
const poppins=Poppins(
  {
    weight:['100','200','400','500','600','800']
  }
)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-gray-50 text-gray-800`}
      >
            <CartProvider>
          <AuthProvider>
        
            <Navbar />
            {children}
          </AuthProvider>

          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
